"""initial schema

Revision ID: 0743dfaa431d
Revises:
Create Date: 2026-08-20 04:13:28.095928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0743dfaa431d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    currencies = op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso_code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("minor_units", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "iso_code ~ '^[A-Z]{3}$'", name="ck_currency_iso_code_format"
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_currency_name_not_empty"),
        sa.CheckConstraint(
            "minor_units >= 0", name="ck_currency_minor_units_not_negative"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso_code", name="uq_currency_iso_code"),
    )
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "rate_date", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("base_currency_id", sa.Integer(), nullable=False),
        sa.Column("quote_currency_id", sa.Integer(), nullable=False),
        sa.Column(
            "side", sa.Enum("BUY", "SELL", name="exchangerateside"), nullable=False
        ),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.CheckConstraint(
            "base_currency_id <> quote_currency_id",
            name="ck_exchange_rate_different_currencies",
        ),
        sa.CheckConstraint("rate > 0", name="ck_exchange_rate_positive"),
        sa.ForeignKeyConstraint(
            ["base_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        currencies,
        [
            {"id": 1, "iso_code": "PHP", "name": "Philippine Peso", "minor_units": 2},
            {
                "id": 2,
                "iso_code": "USD",
                "name": "United States Dollar",
                "minor_units": 2,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange_rates")
    op.drop_table("currencies")
    # ### end Alembic commands ###
