services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql+psycopg://${DB_USER:?No DB_USER defined}:${DB_PASS:?No DB_PASS defined}@db:5432/${DB_NAME:?No DB_NAME defined}
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:?No DB_NAME defined}
      POSTGRES_USER: ${DB_USER:?No DB_USER defined}
      POSTGRES_PASSWORD: ${DB_PASS:?No DB_PASS defined}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:?No DB_USER defined} -d ${DB_NAME:?No DB_NAME defined}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
