from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class DailyRateUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rate=None):  # noqa: E501
        """DailyRateUpdate - a model defined in OpenAPI

        :param rate: The rate of this DailyRateUpdate.  # noqa: E501
        :type rate: str
        """
        self.openapi_types = {
            'rate': str
        }

        self.attribute_map = {
            'rate': 'rate'
        }

        self._rate = rate

    @classmethod
    def from_dict(cls, dikt) -> 'DailyRateUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DailyRateUpdate of this DailyRateUpdate.  # noqa: E501
        :rtype: DailyRateUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rate(self) -> str:
        """Gets the rate of this DailyRateUpdate.

        Positive decimal value represented as a string.  # noqa: E501

        :return: The rate of this DailyRateUpdate.
        :rtype: str
        """
        return self._rate

    @rate.setter
    def rate(self, rate: str):
        """Sets the rate of this DailyRateUpdate.

        Positive decimal value represented as a string.  # noqa: E501

        :param rate: The rate of this DailyRateUpdate.
        :type rate: str
        """
        if rate is None:
            raise ValueError("Invalid value for `rate`, must not be `None`")  # noqa: E501
        if rate is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', rate):  # noqa: E501
            raise ValueError(r"Invalid value for `rate`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._rate = rate
