from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transaction_side import TransactionSide
import re
from openapi_server import util

from openapi_server.models.transaction_side import TransactionSide  # noqa: E501
import re  # noqa: E501

class FxTransaction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, transaction_id=None, timestamp=None, base_currency=None, quote_currency=None, side=None, foreign_amount=None, base_amount=None, effective_rate=None, fee_amount=None, rounding_adjustment=None):  # noqa: E501
        """FxTransaction - a model defined in OpenAPI

        :param transaction_id: The transaction_id of this FxTransaction.  # noqa: E501
        :type transaction_id: str
        :param timestamp: The timestamp of this FxTransaction.  # noqa: E501
        :type timestamp: datetime
        :param base_currency: The base_currency of this FxTransaction.  # noqa: E501
        :type base_currency: str
        :param quote_currency: The quote_currency of this FxTransaction.  # noqa: E501
        :type quote_currency: str
        :param side: The side of this FxTransaction.  # noqa: E501
        :type side: TransactionSide
        :param foreign_amount: The foreign_amount of this FxTransaction.  # noqa: E501
        :type foreign_amount: str
        :param base_amount: The base_amount of this FxTransaction.  # noqa: E501
        :type base_amount: str
        :param effective_rate: The effective_rate of this FxTransaction.  # noqa: E501
        :type effective_rate: str
        :param fee_amount: The fee_amount of this FxTransaction.  # noqa: E501
        :type fee_amount: str
        :param rounding_adjustment: The rounding_adjustment of this FxTransaction.  # noqa: E501
        :type rounding_adjustment: str
        """
        self.openapi_types = {
            'transaction_id': str,
            'timestamp': datetime,
            'base_currency': str,
            'quote_currency': str,
            'side': TransactionSide,
            'foreign_amount': str,
            'base_amount': str,
            'effective_rate': str,
            'fee_amount': str,
            'rounding_adjustment': str
        }

        self.attribute_map = {
            'transaction_id': 'transaction_id',
            'timestamp': 'timestamp',
            'base_currency': 'base_currency',
            'quote_currency': 'quote_currency',
            'side': 'side',
            'foreign_amount': 'foreign_amount',
            'base_amount': 'base_amount',
            'effective_rate': 'effective_rate',
            'fee_amount': 'fee_amount',
            'rounding_adjustment': 'rounding_adjustment'
        }

        self._transaction_id = transaction_id
        self._timestamp = timestamp
        self._base_currency = base_currency
        self._quote_currency = quote_currency
        self._side = side
        self._foreign_amount = foreign_amount
        self._base_amount = base_amount
        self._effective_rate = effective_rate
        self._fee_amount = fee_amount
        self._rounding_adjustment = rounding_adjustment

    @classmethod
    def from_dict(cls, dikt) -> 'FxTransaction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FxTransaction of this FxTransaction.  # noqa: E501
        :rtype: FxTransaction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_id(self) -> str:
        """Gets the transaction_id of this FxTransaction.

        Internal transaction identifier.  # noqa: E501

        :return: The transaction_id of this FxTransaction.
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: str):
        """Sets the transaction_id of this FxTransaction.

        Internal transaction identifier.  # noqa: E501

        :param transaction_id: The transaction_id of this FxTransaction.
        :type transaction_id: str
        """
        if transaction_id is None:
            raise ValueError("Invalid value for `transaction_id`, must not be `None`")  # noqa: E501

        self._transaction_id = transaction_id

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this FxTransaction.


        :return: The timestamp of this FxTransaction.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this FxTransaction.


        :param timestamp: The timestamp of this FxTransaction.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def base_currency(self) -> str:
        """Gets the base_currency of this FxTransaction.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The base_currency of this FxTransaction.
        :rtype: str
        """
        return self._base_currency

    @base_currency.setter
    def base_currency(self, base_currency: str):
        """Sets the base_currency of this FxTransaction.

        ISO-style three-letter currency code.  # noqa: E501

        :param base_currency: The base_currency of this FxTransaction.
        :type base_currency: str
        """
        if base_currency is None:
            raise ValueError("Invalid value for `base_currency`, must not be `None`")  # noqa: E501
        if base_currency is not None and len(base_currency) > 3:
            raise ValueError("Invalid value for `base_currency`, length must be less than or equal to `3`")  # noqa: E501
        if base_currency is not None and len(base_currency) < 3:
            raise ValueError("Invalid value for `base_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if base_currency is not None and not re.search(r'^[A-Z]{3}$', base_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `base_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._base_currency = base_currency

    @property
    def quote_currency(self) -> str:
        """Gets the quote_currency of this FxTransaction.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The quote_currency of this FxTransaction.
        :rtype: str
        """
        return self._quote_currency

    @quote_currency.setter
    def quote_currency(self, quote_currency: str):
        """Sets the quote_currency of this FxTransaction.

        ISO-style three-letter currency code.  # noqa: E501

        :param quote_currency: The quote_currency of this FxTransaction.
        :type quote_currency: str
        """
        if quote_currency is None:
            raise ValueError("Invalid value for `quote_currency`, must not be `None`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) > 3:
            raise ValueError("Invalid value for `quote_currency`, length must be less than or equal to `3`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) < 3:
            raise ValueError("Invalid value for `quote_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if quote_currency is not None and not re.search(r'^[A-Z]{3}$', quote_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `quote_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._quote_currency = quote_currency

    @property
    def side(self) -> TransactionSide:
        """Gets the side of this FxTransaction.


        :return: The side of this FxTransaction.
        :rtype: TransactionSide
        """
        return self._side

    @side.setter
    def side(self, side: TransactionSide):
        """Sets the side of this FxTransaction.


        :param side: The side of this FxTransaction.
        :type side: TransactionSide
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def foreign_amount(self) -> str:
        """Gets the foreign_amount of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :return: The foreign_amount of this FxTransaction.
        :rtype: str
        """
        return self._foreign_amount

    @foreign_amount.setter
    def foreign_amount(self, foreign_amount: str):
        """Sets the foreign_amount of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :param foreign_amount: The foreign_amount of this FxTransaction.
        :type foreign_amount: str
        """
        if foreign_amount is None:
            raise ValueError("Invalid value for `foreign_amount`, must not be `None`")  # noqa: E501
        if foreign_amount is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', foreign_amount):  # noqa: E501
            raise ValueError(r"Invalid value for `foreign_amount`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._foreign_amount = foreign_amount

    @property
    def base_amount(self) -> str:
        """Gets the base_amount of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :return: The base_amount of this FxTransaction.
        :rtype: str
        """
        return self._base_amount

    @base_amount.setter
    def base_amount(self, base_amount: str):
        """Sets the base_amount of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :param base_amount: The base_amount of this FxTransaction.
        :type base_amount: str
        """
        if base_amount is None:
            raise ValueError("Invalid value for `base_amount`, must not be `None`")  # noqa: E501
        if base_amount is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', base_amount):  # noqa: E501
            raise ValueError(r"Invalid value for `base_amount`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._base_amount = base_amount

    @property
    def effective_rate(self) -> str:
        """Gets the effective_rate of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :return: The effective_rate of this FxTransaction.
        :rtype: str
        """
        return self._effective_rate

    @effective_rate.setter
    def effective_rate(self, effective_rate: str):
        """Sets the effective_rate of this FxTransaction.

        Positive decimal value represented as a string.  # noqa: E501

        :param effective_rate: The effective_rate of this FxTransaction.
        :type effective_rate: str
        """
        if effective_rate is None:
            raise ValueError("Invalid value for `effective_rate`, must not be `None`")  # noqa: E501
        if effective_rate is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', effective_rate):  # noqa: E501
            raise ValueError(r"Invalid value for `effective_rate`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._effective_rate = effective_rate

    @property
    def fee_amount(self) -> str:
        """Gets the fee_amount of this FxTransaction.

        Decimal value represented as a string to preserve exact decimal precision and avoid floating-point rounding errors.   # noqa: E501

        :return: The fee_amount of this FxTransaction.
        :rtype: str
        """
        return self._fee_amount

    @fee_amount.setter
    def fee_amount(self, fee_amount: str):
        """Sets the fee_amount of this FxTransaction.

        Decimal value represented as a string to preserve exact decimal precision and avoid floating-point rounding errors.   # noqa: E501

        :param fee_amount: The fee_amount of this FxTransaction.
        :type fee_amount: str
        """
        if fee_amount is None:
            raise ValueError("Invalid value for `fee_amount`, must not be `None`")  # noqa: E501
        if fee_amount is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', fee_amount):  # noqa: E501
            raise ValueError(r"Invalid value for `fee_amount`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._fee_amount = fee_amount

    @property
    def rounding_adjustment(self) -> str:
        """Gets the rounding_adjustment of this FxTransaction.

        Decimal value represented as a string to preserve exact decimal precision and avoid floating-point rounding errors.   # noqa: E501

        :return: The rounding_adjustment of this FxTransaction.
        :rtype: str
        """
        return self._rounding_adjustment

    @rounding_adjustment.setter
    def rounding_adjustment(self, rounding_adjustment: str):
        """Sets the rounding_adjustment of this FxTransaction.

        Decimal value represented as a string to preserve exact decimal precision and avoid floating-point rounding errors.   # noqa: E501

        :param rounding_adjustment: The rounding_adjustment of this FxTransaction.
        :type rounding_adjustment: str
        """
        if rounding_adjustment is None:
            raise ValueError("Invalid value for `rounding_adjustment`, must not be `None`")  # noqa: E501
        if rounding_adjustment is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', rounding_adjustment):  # noqa: E501
            raise ValueError(r"Invalid value for `rounding_adjustment`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._rounding_adjustment = rounding_adjustment
