from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transaction_side import TransactionSide
import re
from openapi_server import util

from openapi_server.models.transaction_side import TransactionSide  # noqa: E501
import re  # noqa: E501

class FxTransactionBase(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None, base_currency=None, quote_currency=None, side=None):  # noqa: E501
        """FxTransactionBase - a model defined in OpenAPI

        :param timestamp: The timestamp of this FxTransactionBase.  # noqa: E501
        :type timestamp: datetime
        :param base_currency: The base_currency of this FxTransactionBase.  # noqa: E501
        :type base_currency: str
        :param quote_currency: The quote_currency of this FxTransactionBase.  # noqa: E501
        :type quote_currency: str
        :param side: The side of this FxTransactionBase.  # noqa: E501
        :type side: TransactionSide
        """
        self.openapi_types = {
            'timestamp': datetime,
            'base_currency': str,
            'quote_currency': str,
            'side': TransactionSide
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'base_currency': 'base_currency',
            'quote_currency': 'quote_currency',
            'side': 'side'
        }

        self._timestamp = timestamp
        self._base_currency = base_currency
        self._quote_currency = quote_currency
        self._side = side

    @classmethod
    def from_dict(cls, dikt) -> 'FxTransactionBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FxTransactionBase of this FxTransactionBase.  # noqa: E501
        :rtype: FxTransactionBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this FxTransactionBase.

        Time at which the transaction was executed.  # noqa: E501

        :return: The timestamp of this FxTransactionBase.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this FxTransactionBase.

        Time at which the transaction was executed.  # noqa: E501

        :param timestamp: The timestamp of this FxTransactionBase.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def base_currency(self) -> str:
        """Gets the base_currency of this FxTransactionBase.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The base_currency of this FxTransactionBase.
        :rtype: str
        """
        return self._base_currency

    @base_currency.setter
    def base_currency(self, base_currency: str):
        """Sets the base_currency of this FxTransactionBase.

        ISO-style three-letter currency code.  # noqa: E501

        :param base_currency: The base_currency of this FxTransactionBase.
        :type base_currency: str
        """
        if base_currency is None:
            raise ValueError("Invalid value for `base_currency`, must not be `None`")  # noqa: E501
        if base_currency is not None and len(base_currency) > 3:
            raise ValueError("Invalid value for `base_currency`, length must be less than or equal to `3`")  # noqa: E501
        if base_currency is not None and len(base_currency) < 3:
            raise ValueError("Invalid value for `base_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if base_currency is not None and not re.search(r'^[A-Z]{3}$', base_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `base_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._base_currency = base_currency

    @property
    def quote_currency(self) -> str:
        """Gets the quote_currency of this FxTransactionBase.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The quote_currency of this FxTransactionBase.
        :rtype: str
        """
        return self._quote_currency

    @quote_currency.setter
    def quote_currency(self, quote_currency: str):
        """Sets the quote_currency of this FxTransactionBase.

        ISO-style three-letter currency code.  # noqa: E501

        :param quote_currency: The quote_currency of this FxTransactionBase.
        :type quote_currency: str
        """
        if quote_currency is None:
            raise ValueError("Invalid value for `quote_currency`, must not be `None`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) > 3:
            raise ValueError("Invalid value for `quote_currency`, length must be less than or equal to `3`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) < 3:
            raise ValueError("Invalid value for `quote_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if quote_currency is not None and not re.search(r'^[A-Z]{3}$', quote_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `quote_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._quote_currency = quote_currency

    @property
    def side(self) -> TransactionSide:
        """Gets the side of this FxTransactionBase.


        :return: The side of this FxTransactionBase.
        :rtype: TransactionSide
        """
        return self._side

    @side.setter
    def side(self, side: TransactionSide):
        """Sets the side of this FxTransactionBase.


        :param side: The side of this FxTransactionBase.
        :type side: TransactionSide
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side
