from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transaction_side import TransactionSide
import re
from openapi_server import util

from openapi_server.models.transaction_side import TransactionSide  # noqa: E501
import re  # noqa: E501

class FxTransactionByBaseAmount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None, base_currency=None, quote_currency=None, side=None, base_amount=None):  # noqa: E501
        """FxTransactionByBaseAmount - a model defined in OpenAPI

        :param timestamp: The timestamp of this FxTransactionByBaseAmount.  # noqa: E501
        :type timestamp: datetime
        :param base_currency: The base_currency of this FxTransactionByBaseAmount.  # noqa: E501
        :type base_currency: str
        :param quote_currency: The quote_currency of this FxTransactionByBaseAmount.  # noqa: E501
        :type quote_currency: str
        :param side: The side of this FxTransactionByBaseAmount.  # noqa: E501
        :type side: TransactionSide
        :param base_amount: The base_amount of this FxTransactionByBaseAmount.  # noqa: E501
        :type base_amount: str
        """
        self.openapi_types = {
            'timestamp': datetime,
            'base_currency': str,
            'quote_currency': str,
            'side': TransactionSide,
            'base_amount': str
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'base_currency': 'base_currency',
            'quote_currency': 'quote_currency',
            'side': 'side',
            'base_amount': 'base_amount'
        }

        self._timestamp = timestamp
        self._base_currency = base_currency
        self._quote_currency = quote_currency
        self._side = side
        self._base_amount = base_amount

    @classmethod
    def from_dict(cls, dikt) -> 'FxTransactionByBaseAmount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FxTransactionByBaseAmount of this FxTransactionByBaseAmount.  # noqa: E501
        :rtype: FxTransactionByBaseAmount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this FxTransactionByBaseAmount.

        Time at which the transaction was executed.  # noqa: E501

        :return: The timestamp of this FxTransactionByBaseAmount.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this FxTransactionByBaseAmount.

        Time at which the transaction was executed.  # noqa: E501

        :param timestamp: The timestamp of this FxTransactionByBaseAmount.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def base_currency(self) -> str:
        """Gets the base_currency of this FxTransactionByBaseAmount.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The base_currency of this FxTransactionByBaseAmount.
        :rtype: str
        """
        return self._base_currency

    @base_currency.setter
    def base_currency(self, base_currency: str):
        """Sets the base_currency of this FxTransactionByBaseAmount.

        ISO-style three-letter currency code.  # noqa: E501

        :param base_currency: The base_currency of this FxTransactionByBaseAmount.
        :type base_currency: str
        """
        if base_currency is None:
            raise ValueError("Invalid value for `base_currency`, must not be `None`")  # noqa: E501
        if base_currency is not None and len(base_currency) > 3:
            raise ValueError("Invalid value for `base_currency`, length must be less than or equal to `3`")  # noqa: E501
        if base_currency is not None and len(base_currency) < 3:
            raise ValueError("Invalid value for `base_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if base_currency is not None and not re.search(r'^[A-Z]{3}$', base_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `base_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._base_currency = base_currency

    @property
    def quote_currency(self) -> str:
        """Gets the quote_currency of this FxTransactionByBaseAmount.

        ISO-style three-letter currency code.  # noqa: E501

        :return: The quote_currency of this FxTransactionByBaseAmount.
        :rtype: str
        """
        return self._quote_currency

    @quote_currency.setter
    def quote_currency(self, quote_currency: str):
        """Sets the quote_currency of this FxTransactionByBaseAmount.

        ISO-style three-letter currency code.  # noqa: E501

        :param quote_currency: The quote_currency of this FxTransactionByBaseAmount.
        :type quote_currency: str
        """
        if quote_currency is None:
            raise ValueError("Invalid value for `quote_currency`, must not be `None`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) > 3:
            raise ValueError("Invalid value for `quote_currency`, length must be less than or equal to `3`")  # noqa: E501
        if quote_currency is not None and len(quote_currency) < 3:
            raise ValueError("Invalid value for `quote_currency`, length must be greater than or equal to `3`")  # noqa: E501
        if quote_currency is not None and not re.search(r'^[A-Z]{3}$', quote_currency):  # noqa: E501
            raise ValueError(r"Invalid value for `quote_currency`, must be a follow pattern or equal to `/^[A-Z]{3}$/`")  # noqa: E501

        self._quote_currency = quote_currency

    @property
    def side(self) -> TransactionSide:
        """Gets the side of this FxTransactionByBaseAmount.


        :return: The side of this FxTransactionByBaseAmount.
        :rtype: TransactionSide
        """
        return self._side

    @side.setter
    def side(self, side: TransactionSide):
        """Sets the side of this FxTransactionByBaseAmount.


        :param side: The side of this FxTransactionByBaseAmount.
        :type side: TransactionSide
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def base_amount(self) -> str:
        """Gets the base_amount of this FxTransactionByBaseAmount.

        Positive decimal value represented as a string.  # noqa: E501

        :return: The base_amount of this FxTransactionByBaseAmount.
        :rtype: str
        """
        return self._base_amount

    @base_amount.setter
    def base_amount(self, base_amount: str):
        """Sets the base_amount of this FxTransactionByBaseAmount.

        Positive decimal value represented as a string.  # noqa: E501

        :param base_amount: The base_amount of this FxTransactionByBaseAmount.
        :type base_amount: str
        """
        if base_amount is None:
            raise ValueError("Invalid value for `base_amount`, must not be `None`")  # noqa: E501
        if base_amount is not None and not re.search(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$', base_amount):  # noqa: E501
            raise ValueError(r"Invalid value for `base_amount`, must be a follow pattern or equal to `/^(0|[1-9][0-9]*)(\.[0-9]+)?$/`")  # noqa: E501

        self._base_amount = base_amount
