from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TransactionSide(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BUY = 'BUY'
    SELL = 'SELL'
    def __init__(self):  # noqa: E501
        """TransactionSide - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionSide':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionSide of this TransactionSide.  # noqa: E501
        :rtype: TransactionSide
        """
        return util.deserialize_model(dikt, cls)
